#!/bin/bash
# DigitalOcean Droplet Setup for ChatBot
# $4/month for reliable 24/7 hosting

echo "🌊 DigitalOcean ChatBot Deployment Guide"
echo "========================================"
echo ""
echo "💰 Cost: $4/month (much cheaper than AWS after free tier)"
echo "💾 Specs: 1GB RAM, 1 vCPU, 25GB SSD"
echo "🌍 Global datacenters available"
echo ""

echo "STEP 1: Create DigitalOcean Account"
echo "==================================="
echo "→ Go to https://digitalocean.com"
echo "→ Sign up with email"
echo "→ Add payment method (credit card/PayPal)"
echo "💡 Tip: Use GitHub Student Pack for $200 free credits!"
echo ""

echo "STEP 2: Create Droplet"
echo "======================"
echo "→ Click 'Create' → 'Droplets'"
echo ""
echo "Configuration:"
echo "  • Image: Ubuntu 22.04 (LTS) x64"
echo "  • Plan: Basic"
echo "  • CPU: Regular Intel - $4/month"
echo "  • Size: 1GB / 1 CPU / 25GB SSD"
echo "  • Datacenter: Choose closest to you"
echo "  • Authentication: SSH Key (recommended) or Password"
echo "  • Hostname: chatbot-server"
echo ""

echo "STEP 3: SSH Key Setup (Recommended)"
echo "==================================="
echo "On your local machine:"
echo ""
echo "# Generate SSH key if you don't have one"
echo "ssh-keygen -t rsa -b 4096 -f ~/.ssh/digitalocean_key"
echo ""
echo "# Copy public key"
echo "cat ~/.ssh/digitalocean_key.pub"
echo ""
echo "→ Paste this public key in DigitalOcean during droplet creation"
echo ""

echo "STEP 4: Connect to Your Droplet"
echo "==============================="
echo "After droplet is created, note the IP address"
echo ""
echo "# Connect via SSH"
echo "ssh -i ~/.ssh/digitalocean_key root@YOUR_DROPLET_IP"
echo ""
echo "# Or if using password:"
echo "ssh root@YOUR_DROPLET_IP"
echo ""

echo "STEP 5: Install ChatBot (Run on DigitalOcean server)"
echo "==================================================="
echo ""
echo "Copy and paste this ONE-LINE command on your server:"
echo ""
echo "curl -fsSL https://raw.githubusercontent.com/aneesomar/CVchatbot/master/digitalocean_install.sh | bash"
echo ""
echo "This will automatically:"
echo "• Update your server"
echo "• Install Python, Git, and all dependencies"  
echo "• Install Ollama AI engine"
echo "• Download your chatbot code from GitHub"
echo "• Download the llama3.2:1b AI model"
echo "• Set up auto-start service"
echo "• Configure firewall"
echo "• Start your chatbot"
echo ""
echo "The installation takes about 10-15 minutes."
echo ""
