#!/bin/bash

echo "🌍 Local + Ngrok: How Other Users Access Your Chatbot"
echo "===================================================="

echo "🏠 Your Computer (Host):"
echo "   ┌─────────────────────────┐"
echo "   │  Your Chatbot Running   │"
echo "   │  Streamlit: port 8501   │"
echo "   │  Ollama: port 11434     │"
echo "   └─────────────────────────┘"
echo "            │"
echo "            ▼"
echo "   ┌─────────────────────────┐"
echo "   │       Ngrok Tunnel      │"
echo "   │  Creates secure bridge  │"
echo "   └─────────────────────────┘"
echo "            │"
echo "            ▼"
echo "        🌍 Internet"
echo ""

echo "👥 Other Users Can Access Via:"
echo "   📱 Phone: https://abc123.ngrok.io"
echo "   💻 Laptop: https://abc123.ngrok.io"
echo "   🖥️  Desktop: https://abc123.ngrok.io"
echo "   📊 Same chatbot interface for everyone!"
echo ""

echo "✅ What Users Can Do:"
echo "   🤖 Chat with your AI assistant"
echo "   📄 Ask about your CV and projects"
echo "   💼 Different personality modes"
echo "   📊 All features work exactly the same"
echo ""

echo "🔧 Your Responsibilities:"
echo "   ✅ Keep your computer on and connected"
echo "   ✅ Keep the chatbot app running"
echo "   ✅ Share the Ngrok URL with users"
echo ""

echo "⚡ Performance:"
echo "   🚀 Uses YOUR computer's full power"
echo "   🧠 Your RAM, CPU, and GPU"
echo "   ⚡ Often FASTER than cloud hosting"
echo "   💾 All data stays on your machine"
echo ""

echo "💰 Cost Comparison:"
echo "   🆓 Ngrok Free: 1 tunnel, random URL"
echo "   💵 Ngrok Pro ($8/month): Custom domain, multiple tunnels"
echo "   🔥 Railway/Cloud: $5-20/month + limited resources"
echo ""

echo "🎯 Perfect For:"
echo "   👨‍💼 Job interviews (show your chatbot)"
echo "   👥 Friends and family testing"
echo "   🎓 University projects"
echo "   💼 Client demonstrations"
echo "   🧪 Development and testing"
